### ISSUE TITLE
Compatibility with vk-sys

### ISSUE THREAD

**Issue by kvark** [Osspial/vk-rs#10]
There is great value in standardizing the way Rust projects see Vulkan low-level bindings. It could be achieved by replacing vk-sys with vk_generator configured specifically with the required flags (e.g. strip prefixes, avoid enums - #8, etc). We'd also benefit from simplifying https://github.com/gfx-rs/portability code, leaving only the new bits and having the rest auto-generated.
cc @tomaka @Osspial

**Comment by Osspial** [comment]
All of the apparent issues needed for vk-sys seem to be resolved. I'm going to close this for now, and re-open if something new comes up.
