### ISSUE TITLE
Value for VK_QUEUE_FAMILY_EXTERNAL_KHX doesn't parse

### ISSUE THREAD

**Issue by Osspial** [Osspial/vk-rs#7]
The current vulkan constant parser is pretty badly written. It should be re-written to better account for types and expressions.

**Comment by kvark** [comment]
@Osspial pinging about a priority bump (blocking vulkano adoption)

**Comment by Osspial** [comment]
Fixed in fee1fdd3757a44abf0052c8be25f5fd7bca78f3b
